
greeting: Hello World!
products:
  request:
    limit: 10

fruity/mp-rest/url: https://fruityvice.com
beers/mp-rest/url: https://api.punkapi.com

quarkus:
  hibernate-orm:
    log:
      sql: true
  http:
    host: 0.0.0.0

"%prod":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:default
    hibernate-orm:
      database:
        generation: drop-and-create
      sql-load-script: import.sql